### ISSUE TITLE
Customized CSS support

### ISSUE THREAD

**Issue by jneo8** [J-Siu/hugo-theme-sk3#15]
Hi I am the user of hugo-theme-sk3

I am looking for the customized css feature like this https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033

Is there any way to do this?

**Comment by J-Siu** [comment]
Yes. Let me work on it.

**Comment by jneo8** [comment]
Btw why I need customized css because I want to put my img center like this http://www.ebadf.net/2016/10/19/centering-images-in-hugo/
Do you think this can be the feature of sk3 theme?

**Comment by J-Siu** [comment]
oops, the commit msg closed it.

I did a quick test. But let me know if it works correctly for you.

**Comment by J-Siu** [comment]
> Btw why I need customized css because I want to put my img center like this http://www.ebadf.net/2016/10/19/centering-images-in-hugo/
> Do you think this can be the feature of sk3 theme?

Ah. I was also thinking of making img center by default in the theme.

**Comment by jneo8** [comment]
It work perfectly!!

The img css work too.
Thanks a lot for you help

Please close the issue.

**Comment by J-Siu** [comment]
Closing.
