### ISSUE TITLE
Posts colour an language Code 

### ISSUE THREAD

**Issue by ogansser** [J-Siu/hugo-theme-sk3#28]
Post color and language code will not be translated in the public folder. color and language look different to the landing page. The change in public folder results from changes yesterday.

**Comment by ogansser** [comment]
the start page is ok, rest not.

example: www.gansser.de

**Comment by ogansser** [comment]
in the head.html:

{{with site.Params.color.text}}:root{--color-txt:{{.}};}{{end}}

must be

{{with site.Params.color.text}}:root{--color-text:{{.}};}{{end}}

right?

**Comment by ogansser** [comment]
in my posts there is noch 

<!doctype html>
--
  | <html lang="en-us">

...

in the public folder. Maybe there is a bug in the new Version of blogdown 1.2.

**Comment by J-Siu** [comment]
In https://github.com/J-Siu/blogdown-sk3-test, if I use following in `config.toml`

```
[Params.color]
bg     = "black"
border = "red"
link   = "green"
text   = "orange"
```

Both .md and .rmd pages color correct in the RStudio viewer.

**Comment by J-Siu** [comment]
I am still looking at language code. BTW, can you post the language code/option you using in config.toml?

**Comment by ogansser** [comment]
de


Am Fr., 9. Apr. 2021 um 16:29 Uhr schrieb John Sing Dao Siu <
***@***.***>:

**Comment by ogansser** [comment]
In the viewer everything is OK, but if i transfer it to my webspace the
HTML head seems different in the Rmd files to the md files.


Am Fr., 9. Apr. 2021 um 16:42 Uhr schrieb Oliver Gansser ***@***.***

**Comment by J-Siu** [comment]
> In the viewer everything is OK, but if i transfer it to my webspace the HTML head seems different in the Rmd files to the md files.

It seems theme is not applied to rmd at all.

**Comment by J-Siu** [comment]
Try stop the blogdown server then build the site, that seems to work for me:

```
blogdown::stop_server()
blogdown::build_site(build_rmd = TRUE)
```

**Comment by ogansser** [comment]
Thanks, I have lesson at the moment. Will test this later and write you
back.


Am Fr., 9. Apr. 2021 um 18:42 Uhr schrieb John Sing Dao Siu <
***@***.***>:

**Comment by ogansser** [comment]
Perfect. build_rmd = TRUE was the magic code. Thanks a lot.

Am Fr., 9. Apr. 2021 um 19:18 Uhr schrieb Oliver Gansser ***@***.***

**Comment by J-Siu** [comment]
Thank you for update. Closing this and https://github.com/J-Siu/blogdown-sk3-test/issues/2
